/**
 * Auto-generated by generate-locales.ts
 * Do not edit manually
 */

export const LOCALES = [
  "en",
  "de",
  "da"
] as const;

export const METRIC_NAMES = [
  "migration",
  "dataInEU",
  "downtime",
  "compliant"
] as const;

export const FEATURE_NAMES = [
  "experience",
  "cloudSecOps",
  "compliance",
  "migration",
  "security",
  "cost"
] as const;

export const FEATURES = [
  {
    "name": "experience",
    "iconName": "award"
  },
  {
    "name": "cloudSecOps",
    "iconName": "users"
  },
  {
    "name": "compliance",
    "iconName": "badge-check"
  },
  {
    "name": "migration",
    "iconName": "zap"
  },
  {
    "name": "security",
    "iconName": "shield-check"
  },
  {
    "name": "cost",
    "iconName": "file-text"
  }
] as const;

export const CONTACT = {
  "name": "Victor Getz",
  "role": "CTO",
  "email": "victor.getz@iits-consulting.de",
  "linkedin": "linkedin.com/in/victor-getz",
  "website": "kumo-ops.com"
} as const;

export const LINKS = {
  "certifications": "https://www.open-telekom-cloud.com/en/products-services/core-services/certifications",
  "pricing": "https://calendly.com/victor-getz/kumoops-intro"
} as const;

export type Locale = (typeof LOCALES)[number];
export type MetricName = (typeof METRIC_NAMES)[number];
export type FeatureName = (typeof FEATURE_NAMES)[number];
