/**
 * Auto-generated by generate-locales.ts
 * Do not edit manually
 */

export const METRIC_NAMES = [
  "infraCosts",
  "incident",
  "downtime",
  "sla"
] as const;

export const FEATURE_NAMES = [
  "cloudSecOps",
  "devPlatform",
  "addons",
  "reliability",
  "cloudIndependent",
  "expertise"
] as const;

export type MetricName = (typeof METRIC_NAMES)[number];
export type FeatureName = (typeof FEATURE_NAMES)[number];
