/**
 * Auto-generated by generate-locales.ts
 * Do not edit manually
 */

export const LOCALES = [
  "en",
  "de",
  "fr",
  "es",
  "it",
  "nl",
  "da",
  "sv"
] as const;

export const CATEGORY_NAMES = [
  "recommended",
  "support_operations",
  "security",
  "artificial_intelligence",
  "cloud_specific"
] as const;

export const ADDON_NAMES = [
  "migration",
  "capacity_boost",
  "upgrade_support",
  "managed_databases",
  "git_hosting",
  "argocd_project_mgmt",
  "cloud_cost_optimization",
  "message_broker",
  "additional_stage",
  "flex_tm_support_weekend",
  "flex_tm_support",
  "premium_sla_global",
  "premium_sla_eu",
  "c5_testified",
  "vpn_ipsec",
  "container_image_hardening",
  "proactive_patch_mgmt",
  "passive_patch_mgmt",
  "managed_container_registry",
  "waf_management",
  "multi_tenancy",
  "psa_compatibility",
  "psa_itil_support",
  "managed_azure_openai",
  "homeport_ai",
  "rbac_telekom",
  "managed_identities",
  "rbac_azure"
] as const;

export const ADDONS_BY_CATEGORY = [
  {
    "id": "recommended",
    "addons": [
      "migration",
      "capacity_boost",
      "upgrade_support",
      "managed_databases",
      "git_hosting",
      "argocd_project_mgmt",
      "cloud_cost_optimization",
      "message_broker",
      "additional_stage"
    ]
  },
  {
    "id": "support_operations",
    "addons": [
      "flex_tm_support_weekend",
      "flex_tm_support",
      "premium_sla_global",
      "premium_sla_eu"
    ]
  },
  {
    "id": "security",
    "addons": [
      "c5_testified",
      "vpn_ipsec",
      "container_image_hardening",
      "proactive_patch_mgmt",
      "passive_patch_mgmt",
      "managed_container_registry",
      "waf_management",
      "multi_tenancy",
      "psa_compatibility",
      "psa_itil_support"
    ]
  },
  {
    "id": "artificial_intelligence",
    "addons": [
      "managed_azure_openai",
      "homeport_ai"
    ]
  },
  {
    "id": "cloud_specific",
    "addons": [
      "rbac_telekom",
      "managed_identities",
      "rbac_azure"
    ]
  }
] as const;

export type Locale = (typeof LOCALES)[number];
export type CategoryName = (typeof CATEGORY_NAMES)[number];
export type AddonName = (typeof ADDON_NAMES)[number];

export interface Addon {
  label: string;
  pricing: string;
  short_description: string;
  detailed_description: string;
}

export interface Category {
  label: string;
  items: Record<string, Addon>;
}

export interface AddonsData {
  meta: {
    version: string;
    lastUpdated: string;
    description: string;
  };
  categories: Record<string, Category>;
}
